version: '3.7'

services:
    amacry:
      build:
        dockerfile: Dockerfile
        context: ./
      container_name: amacry
      volumes:
        - ./app:/opt/app:rw
        - ./.env:/opt/.env:ro
        - ./${DATA_FILE}:/opt/${DATA_FILE}:ro
      working_dir: /opt
      entrypoint: ['python', '-m', 'app.dash_app']
      ports:
        - ${APP_PORT}:${APP_PORT}
      expose:
        - ${APP_PORT}
      tty: true
      stdin_open: true